### ISSUE TITLE
How to ssh -i into UniFi devices without password

### ISSUE THREAD

**Issue by stephenfranklin** [patricegautier/unifiZabbix#11] opened 2021-01-17 22:53 UTC
The problem I'm having is that the Zabbix agent is showing two problems ("...has not reported statistics..." and "...SSH has not been available for..."). 

I think that is because it must authenticate by password, even when the key is specified.
But I don't see any functionality for a "{$UNIFI_PASSWORD}" in the code, so perhaps I'm missing something here?

I have a USG, Switch, two APs, and my controller is hosted on an AWS instance; I'm running Zabbix on a Raspberry Pi.
The templates and hosts are added, and the Zabbix agent can ping my devices.
And I've added the public key (generated on the zabbix server) to the UniFi controller (Device SSH Authentication).

However, my UniFi SSH password is always required when I run:
`sudo -u zabbix ssh -i my-key-pair yourUserName@oneOfYouUnifiDevicesIP`
or
`sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d <theDeviceIP> -u <yourUnifiUserName> -i <fullPathToYourPrivateKey> -t <UDMP|AP|SWITCH|CK>`
And given the password, those operate as expected.

The Unifi > Device SSH Authentication section doesn't allow for a blank password.
I tried manually changing (in the USG's sshd_config) `PasswordAuthentication yes` to `no` but that didn't remove the password requirement when I `ssh -i`, for some reason. But even if it had, that change would be overwritten upon a USG update.

Any clue as to what I'm missing?

And also, thank you for all this zabbix unifi stuff!

**Comment by patricegautier** [comment] 2021-01-18 03:07
Sounds to me the problem is that you need to copy your private keys over to your devices.  A couple of ways:

This this:

sudo -u zabbix ssh-copy-id -i <path_to_your_privateKey> yourUserName@oneOfYouUnifiDevicesIP

If that succeeds then 

sudo -u zabbix ssh -i my-key-pair yourUserName@oneOfYouUnifiDevicesIP

should let you in without a password.

I would make the documentation more explicit..

**Comment by patricegautier** [comment] 2021-01-18 03:10
Also you are right I am not supporting the password path consistently.. keypairs are a better way to go IMO

**Comment by stephenfranklin** [comment] 2021-01-18 05:44
Thanks for the response. I agree that key pairs are better, but I'm not sure UniFi is letting that happen.
My zabbix public key is definitely on my USG (in `/home/steve/.ssh/authorized_keys`).

In fact it's on there twice. The `ssh-copy-id` command initially failed--permission denied, but then succeeded with the `-f` option, yielding double entries in `authorized_keys`.

And just as a sanity check: We are generating a key pair on the Zabbix server, and then sharing its public key with each device, right? We're not generating a key pair on the USG?

The curious thing about how UniFi works is that if I log into any device other than the USG, there's no `.ssh` directory in the file system, and there's no `user` directory nor even a `/home`. My UniFi switch and APs don't have `ssh-keygen` as a command. The USG has it in `/usr/bin`, but the other devices have only the basic `ssh` command. 

Could it be that recent updates of the EdgeOS kernel are just not supportive of third party monitoring?
(My USG is on 3.10.107-UBNT by the way.)

**Comment by patricegautier** [comment] 2021-01-18 05:56
> And just as a sanity check: We are generating a key pair on the Zabbix server, and then sharing its public key with each device, right? We're not generating a key pair on the USG?

Absolutely.

I have a couple of  USGs on 3.10.107 as well so that's not the problem.

Might it be a permission problem on the key pair on the zabbix server side?  SSH is finicky about that.  It should be:

pi@pi4992:~/.ssh/zabbix $ ls -l
total 20
-rw------- 1 zabbix zabbix 1675 Jul 23 18:57 zb_id_rsa
-rw-r--r-- 1 zabbix zabbix  391 Jul 23 18:57 zb_id_rsa.pub

does 

sudo -u zabbix ssh -v -i my-key-pair yourUserName@oneOfYouUnifiDevicesIP

reveal anything interesting?

**Comment by stephenfranklin** [comment] 2021-01-18 08:21
Thank you. I did have the wrong ownership for the key pair.
So now the UniFI devices are accepting the key and not prompting for the password, which is great.

But ssh was warning that the authenticity of the host can't be established, and prompting to make sure I want to connect, and warning:
```
Failed to add the host to the list of known hosts (/var/lib/zabbix/.ssh/known_hosts).
```

Well that file path didn't exist, so I created it, and made the zabbix and .ssh directories owned by zabbix:zabbix.
That allowed ssh to add the hosts' RSA keys.
So now the ssh connection can happen via the key pair without prompting for the password or for connecting to an unknown host.

However, my initial problem remains -- Zabbix is still alerting "SSH has not been available..."
I'll continue troubleshooting tomorrow.

**Comment by patricegautier** [comment] 2021-01-18 19:25
Ok so now when you run:

sudo -u zabbix /usr/lib/zabbix/externalscripts/mca-dump-short.sh -d <theDeviceIP> -u <yourUnifiUserName> -i <fullPathToYourPrivateKey> -t <UDMP|AP|SWITCH|CK>

what do you see?

**Comment by patricegautier** [comment] 2021-01-18 19:38
and I just realized the doc is misleading on how to set this - will update.

**Comment by stephenfranklin** [comment] 2021-01-18 20:19
Yes, I didn't have the private key included in the path. Thanks again.
But, hilariously, that didn't solve the problem, so there must still be something else I've overlooked.

The mca-dump-short.sh command does dump out JSON with good data.

**Comment by patricegautier** [comment] 2021-01-18 20:41
Time to go and look at the zabbix server log  (/var/log/zabbix/zabbix\_server.log usually)  with  DebugLevel=4 in  /etc/zabbix/zabbix_server.conf. Restart the Zabbix server with sudo service zabbix-server restart..

**Comment by patricegautier** [comment] 2021-01-23 02:30
Hi @stephenfranklin have you been able to solve this one?

**Comment by patricegautier** [comment] 2021-02-19 20:00
closing in absence of new activity..

**Closed by patricegautier** 2021-02-19 20:00 UTC
